### ISSUE TITLE
Backwards incompatibility between ignite 0.4.0.dev20200420 vs 0.2.1 for torch.utils.data.Dataset

### ISSUE THREAD

**Issue by bhedayat** [pytorch/ignite#1022]
## 🐛 Bug description

Hello,
When I run the script below with  ignite version 0.2.1. I get the expected output
```
tensor([1])
tensor([2])
tensor([3])
tensor([4])
tensor([5])
tensor([1])
tensor([2])
tensor([3])
tensor([4])
tensor([5])

```
However when I run same script with Ignite Version 0.4.0.dev20200420 I get the following error

```
Engine run is terminating due to exception: 'DataLoader' object has no attribute '_dataset_kind'.
Traceback (most recent call last):
  File "test_ignite.py", line 84, in <module>
    trainer.run(data_loader, max_epochs=2)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 691, in run
    return self._internal_run()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 803, in _internal_run
    self._handle_exception(e)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 509, in _handle_exception
    raise e
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 786, in _internal_run
    self._setup_engine()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 707, in _setup_engine
    _dataloader_kind = self.state.dataloader._dataset_kind
AttributeError: 'DataLoader' object has no attribute '_dataset_kind'
```

I need to use ignite 0.4.0.dev20200420 to use torch.utils.data.IterableDataset (https://github.com/pytorch/ignite/issues/932#event-3257231397). 
The script is below.
Thank you

```
import torch
from ignite.engine import Engine, Events
from ignite.contrib.handlers import ProgressBar
from ignite.handlers import EarlyStopping
from ignite.metrics import RunningAverage
import pdb


class DatasetUtils:
    def __init__(self, datapoints):
        self.datapoints = datapoints

    def load_data(self):
        for d in self.datapoints:
            return d

    def create_examples(self, data):
        for datapoint in data:
            return datapoint**2

    def __len__(self):
        return len(self.datapoints)

class MyDataset(torch.utils.data.Dataset):
    def __init__(self, datapoints):
        self.datapoints = datapoints

    def __getitem__(self, index):
        return datapoints[index]

    def __len__(self):
        return len(self.datapoints)

datapoints = [1, 2, 3, 4, 5]
helper = DatasetUtils(datapoints)

ds = MyDataset(datapoints)

data_loader = torch.utils.data.DataLoader(ds, num_workers=1, batch_size=1)

def update(engine, batch):
    print(batch)
    return 0

def inference(engine, batch):
    for i in data_loader:
        print(i)

trainer = Engine(update)
validator = Engine(inference)

trainer.run(data_loader, max_epochs=2)
```

## Environment

 - PyTorch Version: 1.2.0
 - Ignite Version 0.4.0.dev20200420':
 - OS: Linux
 - How you installed Ignite: pip
 - Python version: 3.6.5
 - Any other relevant information:

**Comment by vfdev-5** [comment]
@bhedayat thanks for the report! Yes, this should be a bug mix between pytorch and ignite.

There are two solutions:
1) you can simply update ignite to more late nigtly release where Engine is simplified and do not patch dataloader to be deterministic etc

2) If you need to use specifically ignite==0.4.0.dev20200420, then you need update pytorch to a higher version. It works for 1.5.0.


However, it is true that for pytorch 1.2.0 and the latest ignite using `DeterministicEngine` it fails in the same way you described:
```python
import torch
from ignite.engine import Events, Engine
from ignite.engine.deterministic import DeterministicEngine
from ignite.contrib.handlers import ProgressBar
from ignite.handlers import EarlyStopping
from ignite.metrics import RunningAverage
import pdb


class DatasetUtils:
    def __init__(self, datapoints):
        self.datapoints = datapoints

    def load_data(self):
        for d in self.datapoints:
            return d

    def create_examples(self, data):
        for datapoint in data:
            return datapoint**2

    def __len__(self):
        return len(self.datapoints)

class MyDataset(torch.utils.data.Dataset):
    def __init__(self, datapoints):
        self.datapoints = datapoints

    def __getitem__(self, index):
        return datapoints[index]

    def __len__(self):
        return len(self.datapoints)

datapoints = [1, 2, 3, 4, 5]
helper = DatasetUtils(datapoints)

ds = MyDataset(datapoints)

data_loader = torch.utils.data.DataLoader(ds, num_workers=1, batch_size=1)

def update(engine, batch):
    print(batch)
    return 0

def inference(engine, batch):
    for i in data_loader:
        print(i)

trainer = DeterministicEngine(update)
validator = Engine(inference)

trainer.run(data_loader, max_epochs=2)
```
