### ISSUE TITLE
0.4.0-pre import ignite broken on Windows machine with cpu-only

### ISSUE THREAD

**Issue by jkhenning** [pytorch/ignite#1110]
## 🐛 Bug description

`import ignite` fails with the following exception:
```
>>> import ignite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Foo\anaconda3\envs\ignite\lib\site-packages\ignite\__init__.py", line 2, in <module>
    import ignite.distributed
  File "C:\Users\Foo\anaconda3\envs\ignite\lib\site-packages\ignite\distributed\__init__.py", line 1, in <module>
    from ignite.distributed.utils import *
  File "C:\Users\Foo\anaconda3\envs\ignite\lib\site-packages\ignite\distributed\utils.py", line 9, in <module>
    from ignite.distributed.comp_models import _SerialModel, has_xla_support, registered_computation_models
  File "C:\Users\Foo\anaconda3\envs\ignite\lib\site-packages\ignite\distributed\comp_models\__init__.py", line 2, in <module>
    from ignite.distributed.comp_models.native import _NativeDistModel
  File "C:\Users\Foo\anaconda3\envs\ignite\lib\site-packages\ignite\distributed\comp_models\native.py", line 13, in <module>
    class _NativeDistModel(ComputationModel):
  File "C:\Users\Foo\anaconda3\envs\ignite\lib\site-packages\ignite\distributed\comp_models\native.py", line 33, in _NativeDistModel
    for name in [dist.Backend.NCCL, dist.Backend.GLOO, dist.Backend.MPI]
AttributeError: module 'torch.distributed' has no attribute 'Backend'
```
When using ignite 0.4.0 pre-release on a Windows machine with no GPU (i.e. cpu-only)

## Environment

 - PyTorch Version (e.g., 1.4): 1.5.0
 - Ignite Version (e.g., 0.3.0): 0.4.0 pre-release
 - OS (e.g., Linux): Windows 10
 - How you installed Ignite (`conda`, `pip`, source): `conda install ignite -c pytorch-nightly`
 - Python version: 3.6.10
 - Any other relevant information:
   - Machine has no GPU, using CPU-only
   - Installed from scratch on a new, clean conda environment

**Comment by sdesrozis** [comment]
@jkhenning Thank you for reporting this bug. I suppose that it miss some guards around idist usage...
