### ISSUE TITLE
[Feature] Add a more comprehensive traceback

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#139]
When developing, it would really helpful to have some more info when something goes wrong with a fired handler. For example, see this traceback
```
Traceback (most recent call last):
  File "cifar10_train_playground.py", line 284, in <module>
    args.lr, args.gamma, args.log_interval, args.output, args.debug)
  File "cifar10_train_playground.py", line 254, in run
    trainer.run(train_loader, max_epochs=epochs)
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 150, in run
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 116, in _handle_exception
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 141, in run
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 85, in _fire_event
  File "cifar10_train_playground.py", line 213, in log_validation_results
    evaluator.run(val_loader)
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 150, in run
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 116, in _handle_exception
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 143, in run
  File "/usr/local/lib/python3.5/dist-packages/ignite-0.1.0a1-py3.5.egg/ignite/engines/engine.py", line 85, in _fire_event
TypeError: __call__() takes 2 positional arguments but 3 were given
```
which is related with the fact that a handler signature is different from the assigned by user:
```python
    handler = EarlyStopping(patience=10, score_function=score_function, trainer=trainer)
    evaluator.add_event_handler(Events.COMPLETED, handler, TRAINER) # No more trainer in the API
```

Maybe, when adding an event handler we could try to execute it and check somehow the signature?

**Comment by vfdev-5** [comment]
@alykhantejani I think we can close this one too
