### ISSUE TITLE
cannot load from older state  

### ISSUE THREAD

**Issue by ttpro1995** [pytorch/ignite#1490]
## 🐛 Bug description

Traceback (most recent call last):
  File "experiment_main.py", line 282, in <module>
    Checkpoint.load_objects(to_load=to_load, checkpoint=checkpoint)
  File "/home/zdeploy/anaconda3/envs/thient_pytorch_gpu5/lib/python3.7/site-packages/ignite/handlers/checkpoint.py", line 233, in load_objects
    obj.load_state_dict(checkpoint[k])
  File "/home/zdeploy/anaconda3/envs/thient_pytorch_gpu5/lib/python3.7/site-packages/ignite/engine/engine.py", line 759, in load_state_dict
    .format(k, state_dict.keys()))
ValueError: Required state attribute 'seed' is absent in provided state_dict 'odict_keys(['epoch_length', 'max_epochs', 'iteration'])'

## Environment
```python
>>> torch.__version__
'1.5.0'
>>> ignite.__version__
'0.3.0'
```

**Comment by vfdev-5** [comment]
@ttpro1995 thanks for the report. Please update to the recent ignite version, e.g. 0.4.2

**Comment by ttpro1995** [comment]
yes, update to 0.4 seem to fix the problem.
