### ISSUE TITLE
[CI] Problem with visdom server launch in travis

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#183]
This issue is to anticipate future failed CI problem for future PRs.

It seems that something wrong again with `.travis.yml`, see the [log](https://travis-ci.org/pytorch/ignite/jobs/377676063)
```
$ python -c "from visdom.server import download_scripts; download_scripts()"
Downloading scripts. It might take a while.
The command "python -c "from visdom.server import download_scripts; download_scripts()"" exited with 0.

$ python -m visdom.server &
The command "python -m visdom.server &" exited with 0.

$ sleep 10
Downloading scripts. It might take a while.
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097

$ python examples/mnist_with_visdom.py --epochs=1
INFO:tornado.access:101 GET /vis_socket (127.0.0.1) 1.04ms
INFO:root:Opened visdom socket from ip: 127.0.0.1
INFO:tornado.access:200 POST /win_exists (127.0.0.1) 0.55ms
Traceback (most recent call last):
  File "examples/mnist_with_visdom.py", line 139, in <module>
    run(args.batch_size, args.val_batch_size, args.epochs, args.lr, args.momentum, args.log_interval)
  File "examples/mnist_with_visdom.py", line 58, in run
    raise RuntimeError("Visdom server not running. Please run python -m visdom.server")
RuntimeError: Visdom server not running. Please run python -m visdom.server
The command "python examples/mnist_with_visdom.py --epochs=1" exited with 1.
```

Maybe it can be easily solved with `sleep 20`, however it would be better to find another solution 

**EDIT**: Problem is related to the new version of visdom 0.1.8.1 , [issue on visdom](https://github.com/facebookresearch/visdom/issues/350)

**Comment by vfdev-5** [comment]
A workaround can be to add `time.sleep(2)` in `mnist_with_visdom.py` between : 
```python
    vis = visdom.Visdom()
    time.sleep(2)
    if not vis.check_connection():
        raise RuntimeError("Visdom server not running. Please run python -m visdom.server")
```
to take a bit of time to initialize the connection with the server.

**Comment by vfdev-5** [comment]
Closed as [visdom issue](https://github.com/facebookresearch/visdom/issues/350) is fixed
