### ISSUE TITLE
Fix warnings in CI

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2018]
## 🚀 Feature

Recent PRs while moving modules from contrib to core introduced few warnings to fix:
- https://github.com/pytorch/ignite/runs/2694096058#step:12:2268
```
  /home/runner/work/ignite/ignite/ignite/contrib/handlers/__init__.py:2: DeprecationWarning: /home/runner/work/ignite/ignite/ignite/contrib/handlers/lr_finder.py has been moved to /ignite/handlers/lr_finder.py and will be removed in version 0.6.0.
   Please refer to the documentation for more details.
    from ignite.contrib.handlers.lr_finder import FastaiLRFinder
```
- https://github.com/pytorch/ignite/runs/2694096058#step:12:2274
```
  /home/runner/work/ignite/ignite/ignite/contrib/handlers/__init__.py:5: DeprecationWarning: /home/runner/work/ignite/ignite/ignite/contrib/handlers/param_scheduler.py has been moved to /ignite/handlers/param_scheduler.py and will be removed in version 0.6.0.
   Please refer to the documentation for more details.
    from ignite.contrib.handlers.param_scheduler import (
```

Other warnings to fix:
- https://github.com/pytorch/ignite/runs/2694096324#step:12:808
- https://github.com/pytorch/ignite/runs/2694096324#step:12:812
```
tests\ignite\handlers\test_checkpoint.py:4
  D:\a\ignite\ignite\tests\ignite\handlers\test_checkpoint.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Mapping, OrderedDict

tests/ignite/test_utils.py::test_deprecated
  D:\a\ignite\ignite\tests\ignite\test_utils.py:221: DeprecationWarning: This function has been deprecated since version 0.4.2 and will be removed in version 0.6.0.
   Please refer to the documentation for more details.
    assert func_check_warning() == 24
```

- https://github.com/pytorch/ignite/runs/2694096324#step:12:1220 (lr_finder)
- https://github.com/pytorch/ignite/runs/2694096324#step:12:1225 (lr_finder)
- https://github.com/pytorch/ignite/runs/2694096324#step:12:1230 (lr_finder)
```
 tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_unexpected_curve
  c:\miniconda3\envs\test\lib\site-packages\torch\nn\modules\loss.py:528: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
    return F.mse_loss(input, target, reduction=self.reduction)

tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_single_param_group
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_multiple_param_groups
  D:\a\ignite\ignite\ignite\handlers\lr_finder.py:305: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
    min_loss_idx = torch.tensor(loss).argmin()

tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_single_param_group
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_multiple_param_groups
  D:\a\ignite\ignite\ignite\handlers\lr_finder.py:310: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
    losses = torch.tensor(decreasing_losses)

tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_mnist
  c:\miniconda3\envs\test\lib\site-packages\torchvision\datasets\mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:143.)
    return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)

tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_mnist
tests/ignite/contrib/handlers/test_lr_finder.py::test_apply_suggested_lr_multiple_param_groups
  D:\a\ignite\ignite\ignite\handlers\lr_finder.py:164: UserWarning: Run completed without loss diverging, increase end_lr, decrease diverge_th or look at lr_finder.plot()
    warnings.warn(

tests/ignite/contrib/handlers/test_lr_finder.py::test_plot_single_param_group
tests/ignite/contrib/handlers/test_lr_finder.py::test_plot_multiple_param_groups
  D:\a\ignite\ignite\ignite\handlers\lr_finder.py:293: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
    plt.show()
```

@KickItLikeShika can you repro lr_finder related warnings locally and fix them please ?

Other warnings:
```
tests/ignite/contrib/metrics/test_precision_recall_curve.py::test_precision_recall_curve
  D:\a\ignite\ignite\tests\ignite\contrib\metrics\test_precision_recall_curve.py:31: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np_y = np.zeros((size,), dtype=np.long)

tests/ignite/contrib/metrics/test_precision_recall_curve.py::test_integration_precision_recall_curve_with_output_transform
  D:\a\ignite\ignite\tests\ignite\contrib\metrics\test_precision_recall_curve.py:52: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np_y = np.zeros((size,), dtype=np.long)

tests/ignite/contrib/metrics/test_precision_recall_curve.py::test_integration_precision_recall_curve_with_activated_output_transform
  D:\a\ignite\ignite\tests\ignite\contrib\metrics\test_precision_recall_curve.py:85: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np_y = np.zeros((size,), dtype=np.long)

tests/ignite/contrib/metrics/test_roc_curve.py::test_roc_curve
  D:\a\ignite\ignite\tests\ignite\contrib\metrics\test_roc_curve.py:28: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np_y = np.zeros((size,), dtype=np.long)

tests/ignite/contrib/metrics/test_roc_curve.py::test_integration_roc_curve_with_output_transform
  D:\a\ignite\ignite\tests\ignite\contrib\metrics\test_roc_curve.py:49: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np_y = np.zeros((size,), dtype=np.long)

tests/ignite/contrib/metrics/test_roc_curve.py::test_integration_roc_curve_with_activated_output_transform
  D:\a\ignite\ignite\tests\ignite\contrib\metrics\test_roc_curve.py:82: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np_y = np.zeros((size,), dtype=np.long)

tests/ignite/engine/test_create_supervised.py::test_create_supervised_training_scalar_assignment
  c:\miniconda3\envs\test\lib\site-packages\torch\cuda\amp\grad_scaler.py:116: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
    warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
```

**Comment by KickItLikeShika** [comment]
Thanks for raising that! 
I will work on this asap, but the deprecation warnings are supposed to be the same, right?

**Comment by vfdev-5** [comment]
> I will work on this asap, but the deprecation warnings are supposed to be the same, right?

@KickItLikeShika well, on linux ci build I do not see the same issues as on windows ci build. Technically, they should be the same...

**Comment by afzal442** [comment]
Hi @KickItLikeShika, as I noticed from the earliest PR, some of the warnings are fixed. Could you plz add here the remaining ones for better understanding to be taken up by someone[new contributors specifically]? I just spent long hours to figure out. Thanks.

**Comment by KickItLikeShika** [comment]
Hi @afzal442, thanks for you interest!
LRFinder related warnings still need to be fixed.

- https://github.com/pytorch/ignite/runs/2734075817#step:12:1241
```
tests/ignite/contrib/handlers/test_lr_finder.py::test_attach_incorrect_input_args
tests/ignite/contrib/handlers/test_lr_finder.py::test_with_attach
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_policy
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_unexpected_curve
/usr/share/miniconda3/envs/test/lib/python3.6/site-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
    return F.mse_loss(input, target, reduction=self.reduction)
```

- https://github.com/pytorch/ignite/runs/2734075817#step:12:1246
```
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_single_param_group
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_multiple_param_groups
/home/runner/work/ignite/ignite/ignite/handlers/lr_finder.py:305: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
    min_loss_idx = torch.tensor(loss).argmin()
```

- https://github.com/pytorch/ignite/runs/2734075817#step:12:1251
```
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_single_param_group
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_multiple_param_groups
  /home/runner/work/ignite/ignite/ignite/handlers/lr_finder.py:310: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
    losses = torch.tensor(decreasing_losses)
```

- https://github.com/pytorch/ignite/runs/2734075817#step:12:1255
```
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_mnist
  /usr/share/miniconda3/envs/test/lib/python3.6/site-packages/torchvision/datasets/mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554793142/work/torch/csrc/utils/tensor_numpy.cpp:143.)
    return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
```

- https://github.com/pytorch/ignite/runs/2734075817#step:12:1260
```
tests/ignite/contrib/handlers/test_lr_finder.py::test_lr_suggestion_mnist
tests/ignite/contrib/handlers/test_lr_finder.py::test_apply_suggested_lr_multiple_param_groups
  /home/runner/work/ignite/ignite/ignite/handlers/lr_finder.py:167: UserWarning: Run completed without loss diverging, increase end_lr, decrease diverge_th or look at lr_finder.plot()
    UserWarning,
```

And you can check other warnings from the links above..
If you would like to like to work on this, please check the discussion here #2023, and you can ask question on our Discord server.
