### ISSUE TITLE
config file not find

### ISSUE THREAD

**Issue by riyaj8888** [pytorch/ignite#2209]
i dont find config file. from where it is imported do anyone have idea.

**Comment by vfdev-5** [comment]
@riyaj8888 If you are talking about this `config`:
https://github.com/pytorch/ignite/blob/053411d73047e278f22008f9f0f1775d0e51dcd5/examples/contrib/cifar10/main.py#L21

It is fetched from local args here:
https://github.com/pytorch/ignite/blob/053411d73047e278f22008f9f0f1775d0e51dcd5/examples/contrib/cifar10/main.py#L191-L193

**Comment by riyaj8888** [comment]
is it required to pass config file always? because most of function has config as arguments .

**Comment by riyaj8888** [comment]
do we always need to implement training function for parallel run

**Comment by vfdev-5** [comment]
> is it required to pass config file always? because most of function has config as arguments .

In general, it can be helpful to have configuration file but not always necessary. Config as argument is one way to implement things. Another way would be to specify all required args directly without grouping them into config dict.

> do we always need to implement training function for parallel run

If we would like to do parallel computations with [ignite support backends] then yes, we need to create a function, like `training`. See more details [here](https://pytorch.org/ignite/distributed.html) or [here](https://pytorch-ignite.ai/posts/distributed-made-easy-with-ignite/).

**Comment by riyaj8888** [comment]
i am getting this error after made changes according to "https://colab.research.google.com/github/pytorch/ignite/blob/master/assets/tldr/teaser.ipynb#scrollTo=bCK9z8MD--zQ"

`2021-09-23 14:27:49,272 ignite.distributed.auto.auto_dataloader INFO: Use data loader kwargs for dataset '<src.datasets.damage':
        {'batch_size': 1, 'num_workers': 8, 'pin_memory': True, 'drop_last': True}
2021-09-23 14:27:55,762 ignite.distributed.auto.auto_dataloader INFO: Use data loader kwargs for dataset '<src.datasets.damage':
        {'batch_size': 1, 'num_workers': 8, 'pin_memory': True, 'drop_last': False}
2021-09-23 14:27:55,762 ignite.distributed.launcher.Parallel INFO: Initialized distributed launcher with backend: 'gloo'
2021-09-23 14:27:55,762 ignite.distributed.launcher.Parallel INFO: - Parameters to spawn processes:
        nproc_per_node: 1
        nnodes: 1
        node_rank: 0
2021-09-23 14:27:55,763 ignite.distributed.launcher.Parallel INFO: Spawn function '<function training at 0x7f4eabca0700>' in 1 processes
2021-09-23 14:28:03,286 ignite.distributed.auto.auto_dataloader INFO: Use data loader kwargs for dataset '<src.datasets.damage':
        {'batch_size': 1, 'num_workers': 8, 'pin_memory': True, 'drop_last': True}
2021-09-23 14:28:09,725 ignite.distributed.auto.auto_dataloader INFO: Use data loader kwargs for dataset '<src.datasets.damage':
        {'batch_size': 1, 'num_workers': 8, 'pin_memory': True, 'drop_last': False}
2021-09-23 14:28:09,726 ignite.distributed.launcher.Parallel INFO: Initialized distributed launcher with backend: 'gloo'
2021-09-23 14:28:09,726 ignite.distributed.launcher.Parallel INFO: - Parameters to spawn processes:
        nproc_per_node: 1
        nnodes: 1
        node_rank: 0
2021-09-23 14:28:09,726 ignite.distributed.launcher.Parallel INFO: Spawn function '<function training at 0x7ff75ae46ca0>' in 1 processes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/Event_project/Prior_Data_/Prior_Deliverables/ger/src/commands/train/damage_train_idist.py", line 201, in <module>
    parallel.run(training)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/ignite/distributed/launcher.py", line 271, in run
    idist.spawn(self.backend, func, args=args, kwargs_dict=kwargs, **self._spawn_params)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/ignite/distributed/utils.py", line 309, in spawn
    comp_model_cls.spawn(
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/ignite/distributed/comp_models/native.py", line 285, in spawn
    start_processes(
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 148, in start_processes
    process.start()
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "damage_train_idist.py", line 201, in <module>
    parallel.run(training)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/ignite/distributed/launcher.py", line 271, in run
    idist.spawn(self.backend, func, args=args, kwargs_dict=kwargs, **self._spawn_params)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/ignite/distributed/utils.py", line 309, in spawn
    comp_model_cls.spawn(
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/ignite/distributed/comp_models/native.py", line 285, in spawn
    start_processes(
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 110, in join
    raise Exception(
Exception: process 0 terminated with exit code 1
`

**Comment by sdesrozis** [comment]
@riyaj8888 Sorry this is not really easy to help, could you try to get the relevant part of the error message ?

You said you have made a few changes in the original notebook, maybe you could give more details.

Thanks.

**Comment by vfdev-5** [comment]
@riyaj8888 if you are using Jupyter to launch the code, please use `start_method = "fork"`:
```python

import ignite.distributed as idist

def training(local_rank, config, **kwargs):
    # ...
    print(idist.get_rank(), ": run with config:", config, "- backend=", idist.backend())
    # ...

backend = "gloo"
config = {}
with idist.Parallel(backend=backend, start_method = "fork") as parallel:
    parallel.run(training, config, a=1, b=2)
```

**Comment by riyaj8888** [comment]
can you provide sample code/script of distributed training?

what minimum code should be we insert inside 

`def training(local_rank, config, **kwargs):
    # ...
    print(idist.get_rank(), ": run with config:", config, "- backend=", idist.backend())
    # ...

backend = "gloo"
config = {}
with idist.Parallel(backend=backend, start_method = "fork") as parallel:
    parallel.run(training, config, a=1, b=2)`

**Comment by riyaj8888** [comment]
@vfdev-5  
what is a,b in the .run

**Comment by riyaj8888** [comment]
`import ignite.distributed as idist

def train_fn(local_rank, a, b, c):

    import torch.distributed as dist
    assert dist.is_available() and dist.is_initialized()
    assert dist.get_world_size() == 4

    device = idist.device()
    assert device == torch.device(f"cuda:{local_rank}")


backend = "nccl"  # or "gloo" or "horovod" or "xla-tpu"
idist.initialize(backend)
local_rank = idist.get_local_rank()
train_fn(local_rank, a, b, c)
idist.finalize()`

**Comment by riyaj8888** [comment]
https://pytorch.org/ignite/distributed.html

**Comment by vfdev-5** [comment]
@riyaj8888 here is a working code:
```python
import time
import ignite.distributed as idist

def training(local_rank, config, **kwargs):
    # ...
    time.sleep(0.1 * local_rank)
    print(idist.get_rank(), ": run with config:", config, "- backend=", idist.backend())
    # ...

backend = "gloo"
config = {}
with idist.Parallel(backend=backend, start_method="fork", nproc_per_node=2) as parallel:
    parallel.run(training, config, a=1, b=2)
```

`config`, `a`, `b` are example argument that you can remove, replace etc.


PS: @riyaj8888 please write a single message with all your questions such that we wont spam all other users watching this repository.
If you would like to discuss with instant messages, please use our discord server: https://discord.gg/djZtm3EmKj

**Comment by riyaj8888** [comment]
Thanks for your reply.

i have one question sorry for multiple questions,
once we creata training function inside main.py then how do we  do traiining on multiple devices ? can u assist in this

**Comment by vfdev-5** [comment]
Let me close this issue as solved. Feel free to ask other questions on Discord or GH Discussions or in another issue.
