### ISSUE TITLE
TPU CI failure

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2350]
- https://github.com/pytorch/ignite/runs/4484818799

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/torch_xla/__init__.py", line 99, in <module>
    import torch
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
Error: Process completed with exit code 1.
```

**Comment by fco-dv** [comment]
Seems that mkl 2022.0.0 was [released](https://pypi.org/project/mkl/2022.0.0/)  recently and may cause this bug :  
```
Collecting mkl
  Downloading mkl-2022.0.0-py2.py3-none-manylinux1_x86_64.whl (256.0 MB)
```
Maybe we could make a test by setting mkl version to the previous working version in the ci ? `pip install mkl==2021.4.0`
