### ISSUE TITLE
Fix docs building

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/ignite#2464]
## 📚 Documentation

Following https://github.com/pytorch/ignite/pull/2457 docs build is failing due to copying of orphaned defaults.rst file:

- https://github.com/pytorch/ignite/runs/5148163094?check_suite_focus=true
```
 Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/tmp/tmpy5n1diwnsphinxcontrib_versioning/f4ffa27253e329a9d29a679bcba4756f262bcc2d/docs/source/conf.py", line 74, in <module>
    shutil.copy(os.path.join(src_folder, "defaults.rst"), gen_folder)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpy5n1diwnsphinxcontrib_versioning/f4ffa27253e329a9d29a679bcba4756f262bcc2d/docs/source/defaults.rst'

Process Process-2:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 208, in _build
    raise SphinxError
sphinx.errors.SphinxError
=> sphinx-build failed for branch/tag: v0.4.8
Failure.
```

More details on how docs are built:

- https://github.com/pytorch/ignite/blob/master/.github/workflows/install_docs_deps.sh
- https://github.com/pytorch/ignite/blob/master/.github/workflows/build_docs.sh
- https://github.com/pytorch-ignite/sphinxcontrib-versioning

How everything is executed in the CI:
https://github.com/pytorch/ignite/blob/4c2b62bf17aabb998b189b2e39afd59928adf7c1/.github/workflows/docs.yml#L28-L32

**Comment by soma2000-lang** [comment]
Working on this

**Comment by DevPranjal** [comment]
Hey @soma2000-lang, we were discussing about solutions to this issue. One of the workarounds that @vfdev-5 proposed was to skip copying files if it doesn't exist. I have implemented that for now. You could propose any other solution to @vfdev-5 (maybe somehow skip copying `defaults.rst` and make the `master-conf` work for all branches).
