### ISSUE TITLE
multi GPU training problem

### ISSUE THREAD

**Issue by houweidong** [pytorch/ignite#464]

**Comment by vfdev-5** [comment]
Take a look at distributed mnist exemple : https://github.com/pytorch/ignite/tree/master/examples/mnist

**Comment by houweidong** [comment]
Thanks for your reply. Is there need a DistributedSampler as distributed mnist exemple when i training with multi GPU?

**Comment by houweidong** [comment]
when i trained my multi gpu code, i meet the wrong as here:

> /usr/bin/python3.6 /home/new/dev/weidong/CubeModel/train_cube.py -ld baseline -bs 256 -lr 3e-3
Loading models
Loading dataset
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Start training
Epoch[1] Starts with lr=0.003
Traceback (most recent call last):
  File "/home/new/dev/weidong/CubeModel/train_cube.py", line 168, in <module>
    run(args)
  File "/home/new/dev/weidong/CubeModel/train_cube.py", line 160, in run
    trainer.run(train_loader, max_epochs=opt.n_epochs)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 326, in run
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 291, in _handle_exception
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 313, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 280, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 291, in _handle_exception
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/engine.py", line 272, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "/usr/local/lib/python3.6/dist-packages/ignite/engine/__init__.py", line 43, in _update
    y_pred = model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/new/dev/weidong/CubeModel/model/cubenet.py", line 35, in forward
    x = self.feature_extractor(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pretrainedmodels/models/torchvision_models.py", line 322, in features
    x = self.conv1(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)

The model was send to the create_supervised_trainer had been wrapped with nn.DataParallel(model, device_ids=None), but the error happened.

**Comment by houweidong** [comment]
i have solved the problem, it's the pretrainedmodels cause the problem.

**Comment by vfdev-5** [comment]
Glad that you found the solution by yourself :)

**Comment by kamalaVJ** [comment]
@houweidong  How did you solve the error? I am facing the same issue however I'm not using nay pre-trained model.

**Comment by vfdev-5** [comment]
@kamalaVJ can you give more information on your issue ? 
In my case, in multi GPU case with Nvidia apex, I'm wrapping the model using `apex.parallel.DistributedDataParallel` and launch everything with `torch.distributed.launch`. 
We need also to set default cuda device `torch.cuda.set_device(local_rank)`.

Today, there can be an issue with ignite when computing metrics. Results are not collected across GPUs. We are working on this, #573 .

**Comment by kamalaVJ** [comment]
@vfdev-5  I'm wrapping the model using the pytorch DataParallel. I also mention the device ids. I initialize using torch.distributed.init_process_group with backend as nccl. I still end up getting the same error.

**Comment by vfdev-5** [comment]
@kamalaVJ I was suspecting ignite's trainer to be responsible for this. Another question, can you check if the following works for your model and setting:
```python
net = torch.nn.DataParallel(model, device_ids=device_ids)
output = net(input_var)  # input_var can be on any device, including CPU
```
