### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by g-karthik** [pytorch/ignite#540]
Steps to reproduce:

1. pip install --upgrade git+https://github.com/pytorch/ignite.git
2. pip install  --upgrade  git+https://github.com/lanpa/tensorboardX.git
3. Open Python in the terminal and do the following:

```
>>> from ignite.contrib.handlers.tensorboard_logger import TensorboardLogger
>>> tb_logger = TensorboardLogger(log_dir=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/contrib/handlers/tensorboard_logger.py", line 403, in __init__
    from tensorboardX import SummaryWriter
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/writer.py", line 15, in <module>
    from .event_file_writer import EventFileWriter
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/proto/event_pb2.py", line 15, in <module>
    from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/proto/summary_pb2.py", line 15, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/proto/tensor_pb2.py", line 15, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n(tensorboardX/proto/resource_handle.proto\x12\x0ctensorboardX\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

cc @vfdev-5

**Comment by g-karthik** [comment]
Okay, after a bit of messing around, I found that I had to uninstall protobuf and then install tensorboardX and ignite from master. Consequently, when I installed tensorboardX, it did a fresh install of protobuf from PyPI.

```
pip uninstall protobuf
pip install git+https://github.com/lanpa/tensorboardX.git
pip install git+https://github.com/pytorch/ignite.git
```
