### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by gyc521zsc** [pytorch/ignite#578]
python test.py --config_file='/home/gyc/Ranked_Person_ReID-master/configs/softmax_ranked.yml' MODEL.DEVICE_ID "('3')" DATASETS.NAMES "('market1501')" TEST.FEAT_NORM "('yes')" MODEL.PRETRAIN_CHOICE "('self')" TEST.WEIGHT "('/home/gyc/Ranked_Person_ReID-master/modeling/mar_resnet50_ibn_a_model.pth')"
 

Traceback (most recent call last):
  File "test.py", line 67, in <module>
    main()
  File "test.py", line 63, in main
    inference(cfg, model, val_loader, num_query)
  File "/home/gyc/Ranked_Person_ReID-master/engine/inference.py", line 70, in inference
    evaluator.run(val_loader)
  File "/home/gyc/anaconda3/envs/python361/lib/python3.6/site-packages/ignite/engine/engine.py", line 326, in run
    self._handle_exception(e)
  File "/home/gyc/anaconda3/envs/python361/lib/python3.6/site-packages/ignite/engine/engine.py", line 291, in _handle_exception
    raise e
  File "/home/gyc/anaconda3/envs/python361/lib/python3.6/site-packages/ignite/engine/engine.py", line 313, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/home/gyc/anaconda3/envs/python361/lib/python3.6/site-packages/ignite/engine/engine.py", line 280, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/gyc/anaconda3/envs/python361/lib/python3.6/site-packages/ignite/engine/engine.py", line 291, in _handle_exception
    raise e
  File "/home/gyc/anaconda3/envs/python361/lib/python3.6/site-packages/ignite/engine/engine.py", line 272, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "/home/gyc/Ranked_Person_ReID-master/engine/inference.py", line 38, in _inference
    feat = model(data)
  File "/home/gyc/anaconda3/envs/python361/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gyc/Ranked_Person_ReID-master/modeling/baseline.py", line 192, in forward
    x = self.stn(x)    #### stn
TypeError: 'str' object is not callable

请教各位大佬

**Comment by vfdev-5** [comment]
This seems not ignite issue, but the code you use : 
```
/home/gyc/Ranked_Person_ReID-master/modeling/baseline.py
```
