### ISSUE TITLE
Using ProgressBar with IterableDataset 

### ISSUE THREAD

**Issue by bhedayat** [pytorch/ignite#932]
## 🐛 Bug description

Hello,

I cannot get IterableDataset to work with ignite.contrib.handlers.ProgressBar.
I followed https://github.com/pytorch/ignite/issues/618 and was able to successfully run
`trainer.run(map(lambda x: x, train_data_loader), max_epochs=1, epoch_length=2)`.
But when I added ProgressBar as an event_handler i get error below.

```
Traceback (most recent call last):
  File "test_ignite.py", line 70, in <module>
    trainer.run(map(lambda x: x, data_loader), epoch_length=10//10, max_epochs=2)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 850, in run
    return self._internal_run()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 952, in _internal_run
    self._handle_exception(e)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 716, in _handle_exception
    raise e
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 937, in _internal_run
    hours, mins, secs = self._run_once_on_dataset()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 705, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 716, in _handle_exception
    raise e
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 689, in _run_once_on_dataset
    self._fire_event(Events.ITERATION_COMPLETED)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/engine/engine.py", line 607, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/contrib/handlers/tqdm_logger.py", line 225, in __call__
    pbar_total = self.get_max_number_events(event_name, engine)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ignite/contrib/handlers/tqdm_logger.py", line 218, in get_max_number_events
    return len(engine.state.dataloader)
TypeError: object of type 'map' has no len()
```

Here is my use case and replication of the error:

```
import torch
from ignite.engine import Engine, Events
from ignite.contrib.handlers import ProgressBar

class DatasetUtils:
    def __init__(self, datapoints):
        self.datapoints = datapoints

    def load_data(self):
        for d in self.datapoints:
            yield d

    def create_examples(self, data):
        for datapoint in data:
            yield datapoint**2

    def __len__(self):
        return len(self.datapoints)

class MyIterableDataset(torch.utils.data.IterableDataset):
    def __init__(self, helper):
        self.helper = helper

    def __iter__(self):
        data_iter = self.helper.load_data()

        for example in self.helper.create_examples(data_iter):
            yield example

    def __len__(self):
        return len(self.helper)

datapoints = [1, 2, 3, 4, 5]
helper = DatasetUtils(datapoints)

ds = MyIterableDataset(helper)

data_loader = torch.utils.data.DataLoader(ds, num_workers=1)


def update(engine, batch):
    for i in data_loader:
        print(i)

def inference(engine, batch):
    for i in data_loader:
        print(i)

trainer = Engine(update)
validator = Engine(inference)
trainer.add_event_handler(Events.STARTED, lambda _: validator.run(map(lambda x: x, data_loader), epoch_length=10//10))

pbar = ProgressBar(persist=True)
pbar.attach(trainer, metric_names=["loss"])
validator.add_event_handler(Events.COMPLETED, lambda _: pbar.log_message("Valid: %s" % validator.state.metrics))

trainer.run(map(lambda x: x, data_loader), epoch_length=10//10, max_epochs=2)
```
Thank you.

## Environment

 - PyTorch Version (e.g., 1.2):
 - Ignite Version (e.g., 0.3.0):
 - OS (e.g., Linux):
 - How you installed Ignite (`pip`):
 - Python version: 3.6.5

**Comment by vfdev-5** [comment]
@bhedayat thanks for reporting. This bug was previously fixed on master. Please, use nightly release if possible:
```bash
pip uninstall -y pytorch-ignite
pip install --upgrade --pre pytorch-ignite
pip list | grep pytorch-ignite
> pytorch-ignite                0.4.0.dev20200417       
```

**Comment by bhedayat** [comment]
Thank you! When will the stable release become 0.4.0?
